x-common-configuration: &common-configuration
  env_file:
    - .env
  healthcheck:
    interval: 7s
    timeout: 2s
    retries: 5
  networks:
    - default

services:
  api:
    <<: *common-configuration
    container_name: nestjs-backend
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - "8080:8080"
    labels:
      - dev.dozzle.name=backend-nestjs
    volumes:
      - ./src:/usr/src/app/src
    environment:
      DATABASE_HOST: "database"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/api/health-check" ]
    depends_on:
      database:
        condition: service_started

  database:
    <<: *common-configuration
    image: postgis/postgis:17-3.4
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    labels:
      - dev.dozzle.name=postgresql-main
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]

volumes:
  postgres_data:

networks:
  default:
