x-common-configuration: &common-configuration
  env_file:
    - .env
  healthcheck:
    interval: 10s
    timeout: 5s
    retries: 5
  networks:
    - default

services:
  api:
    <<: *common-configuration
    container_name: nestjs-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./src:/usr/src/app/src
    environment:
      DATABASE_HOST: "host.docker.internal"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health-check" ]
    depends_on:
      database:
        condition: service_healthy

  database:
    <<: *common-configuration
    image: postgis/postgis:latest
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]

networks:
  default:
